apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-app
  labels:
    app: my-app
    env: prod
spec:
  # modify replicas according to your case
  replicas: 2
  selector:
    matchLabels:
      app: my-app
      env: prod
  template:
    metadata:
      labels:
        app: my-app
        env: prod
    spec:
      containers:
      - name: n-app
        image: nginx
        ports:
        - containerPort: 80